volumes:
  solr:
  sitemaps:

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      target: base
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
      - sitemaps:/sitemaps
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /app
    command: "npm run dev"
    environment:
      - SOLR_URL=http://solr:8983/solr # without trailing slash
  cli:
    image: oven/bun:1.1-alpine
    volumes:
      - ./cli:/app
      - sitemaps:/sitemaps
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /app
    environment:
      - SOLR_URL=http://solr:8983/solr # without trailing slash
      - SITEMAP_URL_BASE=${SITEMAP_URL_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    profiles:
      - cli
  solr:
    build: ./docker/solr
    volumes:
      - solr:/var/solr
    ports:
      - 8983:8983
    command: "solr-foreground -m 128m"
