volumes:
  solr:
  sitemaps:

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    user: node:node
    environment:
      - SOLR_URL=http://solr:8983/solr # without trailing slash
      - GOOGLE_ADSENSE_CLIENT_ID=${GOOGLE_ADSENSE_CLIENT_ID}
      - GOOGLE_TAG_MANAGER_CONTAINER_ID=${GOOGLE_TAG_MANAGER_CONTAINER_ID}
    labels:
      traefik.enable: true
      # HTTP
      traefik.http.routers.ertelmezoszotar-http.entrypoints: web
      traefik.http.routers.ertelmezoszotar-http.rule: ${TRAEFIK_RULE}
      traefik.http.routers.ertelmezoszotar-http.middlewares: https-redirect@file
      # HTTPS
      traefik.http.routers.ertelmezoszotar.entrypoints: websecure
      traefik.http.routers.ertelmezoszotar.rule: ${TRAEFIK_RULE}
      traefik.http.routers.ertelmezoszotar.tls: true
      traefik.http.routers.ertelmezoszotar.tls.certresolver: ${TRAEFIK_TLS_CERTRESOLVER}
      traefik.http.routers.ertelmezoszotar.middlewares: hsts@file,gzip@file
    volumes:
      - sitemaps:/sitemaps
  cli:
    build:
      dockerfile: ./docker/cli/prod.Dockerfile
      context: .
    volumes:
      - sitemaps:/sitemaps
    environment:
      - SOLR_URL=http://solr:8983/solr # without trailing slash
      - SITEMAP_URL_BASE=${SITEMAP_URL_BASE}
    profiles:
      - cli
  solr:
    build: ./docker/solr
    volumes:
      - solr:/var/solr
    command: "solr-foreground -m 128m"
